version: '3.8'
services:
  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    env_file: ./frontend-service/.env
    ports:
      - "8080:8080"
  catalog:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    env_file: ./catalog-service/.env
    ports:
      - "8081:8081"
  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    env_file: ./order-service/.env
    ports:
      - "8082:8082"