version: '3.8'
services:
  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    env_file: ./frontend-service/.env
    ports:
      - "5000:5000"
    depends_on:
      - catalog1
      - catalog2
      - order1
      - order2

  catalog1:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    env_file: ./catalog-service/.env
    ports:
      - "5001:5001"

  catalog2:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    env_file: ./catalog-service/.env
    ports:
      - "5003:5003"

  order1:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    env_file: ./order-service/.env
    ports:
      - "5002:5002"

  order2:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    env_file: ./order-service/.env
    ports:
      - "5004:5004"
